apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: my-bot-namespace
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: bot
        image: telegram-bot:latest
        imagePullPolicy: Never  # Использует локальный образ
        envFrom:
        - secretRef:
            name: bot-secrets
