name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.5
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull and redeploy on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
        # Обновление кода
        cd ~/telegram-bot
        git pull origin main

        # Переключение на Docker Minikube
        eval $(minikube docker-env)
        
        # Сборка и применение манифестов
        docker build -t telegram-bot:latest .
        kubectl -n my-bot-namespace rollout restart deployment telegram-bot
        ENDSSH
