name: Deploy Telegram Bot to Kubernetesx

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/AntilopaGnu666/telegram-bot:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/AntilopaGnu666/telegram-bot:latest

    - name: Setup kubectl
      uses: azure/setup-k8s@v1
      with:
        namespace: my-bot-namespace
        version: 'latest'

    - name: Update Deployment with new image
      run: |
        kubectl set image deployment/telegram-bot bot=ghcr.io/AntilopaGnu666/telegram-bot:latest --namespace=my-bot-namespace

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/
