name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull code and redeploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
        # Переключаемся на Minikube
        eval $(minikube docker-env)

        # Переходим в папку с проектом
        cd ~/telegram-bot

        # Обновляем код
        git pull origin main

        # Собираем образ
        docker build -t telegram-bot:latest .
        docker tag telegram-bot:latest

        # Перезапускаем Deployment
        kubectl -n my-bot-namespace set image deployment/telegram-bot bot=telegram-bot:latest
        kubectl -n my-bot-namespace rollout restart deployment telegram-bot
        # Удалите все старые образы, кроме текущего
        docker images | grep 'telegram-bot' | grep -v 'latest' | awk '{print $3}' | xargs --no-run-if-empty docker rmi
        ENDSSH
